### ISSUE TITLE
Save State/Rewind

### ISSUE THREAD

**Issue by humbertodias** [Skurdt/LibretroUnityFE#10]
Cool features that could be implemented:

Save state
https://youtu.be/SNQxJhiMah4?t=429

Rewind
https://youtu.be/SNQxJhiMah4?t=482

**Comment by Skurdt** [comment]
(this will not work in opengl cores)

37357cd301b10b2ee29cb48b6269285151e93baa

F5-F8 to save
F9-F12 to load

Backspace to rewind

**Comment by CCIGAMES** [comment]
@Skurdt does this save to a file?
